let path=require("path");
module.exports={
    entry:{
        app:path.resolve(__dirname,"./src/main/app.js"),
        main:path.resolve(__dirname,"./src/main/main.js")
    },
    output:{
        path:path.resolve(__dirname,"./dist"),
        filename:"[name].bundle.js"
    },
    module:{
        rules:[
            {
                test:/\.less$/,
                loader:["style-loader","css-loader","less-loader"]
            },
            {
                test:/\.css$/,
                use:[
                    'style-loader',
                    {
                        loader:"css-loader",
                        /*options:{
                            modules:true
                        }*/
                    }
                ]
            },
            {
                test:/\.jsx?$/,
                exclude:path.resolve(__dirname,"./node_modules/"),
                loader:"babel-loader",
                options:{
                    presets:["es2015","react"]
                }
            }
        ]
    }
}